title: "PrismaORM MIGRATEドキュメント翻訳"
summary: "このドキュメントはPrisma ORMのMigrateに関する公式ドキュメントを翻訳したものです。2025.11時点での情報が含まれています。"
topics: [Prisma, ORM]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
toc_depth: 3
chapters:
  - 1-0
  - 1-1
  - 2-0
  - 2-1
  - 2-2
  - 2-3
  - 2-4
  - 2-5
  - 3-0
  - 3-1
  - 3-2
  - 3-3
  - 3-4
  - 3-5-0
  - 3-5-1
  - 3-5-2
  - 3-6
  - 3-7
  - 3-8
  - 3-9
  - 3-10
  - 3-11
  - 3-12
